require('dotenv').config();
const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const { body, param, validationResult } = require('express-validator');
const rateLimit = require('express-rate-limit');
const helmet = require('helmet');
const shapefile = require('shapefile');
const crypto = require('crypto');
const multer = require('multer');

// Import database service
const DatabaseService = require('./db/database');

// ZIP code data cache (loaded on startup)
let zipcodeData = null;
let zipcodeDataLoaded = false;

// Precomputed CA ZIP adjacency-coloring map (loaded on startup)
// { [zipCode]: hexColor }, generated by scripts/computeZipCaColors.js
let caZipColors = null;

// Load ZIP code shapefile data into memory
async function loadZipcodeData() {
    try {
        console.log('📂 Loading ZIP code boundary data...');
        const startTime = Date.now();

        const shapefileDir = path.join(__dirname, 'MapZipCodes', 'tl_2020_us_zcta520');
        const shpPath = path.join(shapefileDir, 'tl_2020_us_zcta520.shp');

        console.log('🔄 Parsing shapefile data...');

        // Create lookup index for fast access
        zipcodeData = {};
        let count = 0;

        // Read shapefile feature by feature
        const source = await shapefile.open(shpPath);
        let result = await source.read();

        while (!result.done) {
            const feature = result.value;
            const zipCode = feature.properties.ZCTA5CE20;
            if (zipCode) {
                zipcodeData[zipCode] = feature.geometry;
                count++;
            }
            result = await source.read();
        }

        zipcodeDataLoaded = true;
        const loadTime = ((Date.now() - startTime) / 1000).toFixed(2);
        console.log(`✅ Loaded ${count} ZIP codes in ${loadTime} seconds`);
    } catch (error) {
        console.error('❌ Error loading ZIP code data:', error);
        console.error('ZIP code lookups will not be available');
        zipcodeDataLoaded = false;
    }
}

// Load the precomputed CA ZIP adjacency-coloring map (generated by
// scripts/computeZipCaColors.js, committed to the repo since the source
// shapefile is gitignored). Missing file degrades gracefully — the client
// falls back to the default color rather than the server failing to start.
async function loadCaZipColors() {
    try {
        const jsonPath = path.join(__dirname, 'server', 'staticData', 'caZipColors.json');
        const parsed = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        caZipColors = parsed.colors;
        console.log(`✅ Loaded ${Object.keys(caZipColors).length} CA ZIP colors`);
    } catch (error) {
        console.error('⚠️  Could not load CA ZIP color data (run `npm run colors:build`):', error.message);
        caZipColors = {};
    }
}

const app = express();
const PORT = process.env.PORT || 3000;

// Security: Configure CORS with specific origins
const corsOptions = {
    origin: process.env.NODE_ENV === 'production'
        ? ['https://yourdomain.com'] // Replace with your actual domain
        : ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5173', 'http://127.0.0.1:5173'],
    credentials: true,
    optionsSuccessStatus: 200
};

// Security: Use helmet for security headers
app.use(helmet({
    contentSecurityPolicy: false, // Disable for Google Maps
    crossOriginEmbedderPolicy: false
}));

app.use(cors(corsOptions));

// Cookie parser middleware
app.use(cookieParser());

// Security: Rate limiting
const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: process.env.NODE_ENV === 'production' ? 100 : 2000, // higher limit in dev: reload cycles + bulk ZIP lookups exceed 100/15min
    message: 'Too many requests from this IP, please try again later.',
    standardHeaders: true,
    legacyHeaders: false
});
app.use('/api/', limiter);

// Security: Limit JSON payload size
app.use(bodyParser.json({ limit: '10mb' }));

// Validation error handler middleware
const handleValidationErrors = (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(400).json({
            error: 'Validation failed',
            details: errors.array()
        });
    }
    next();
};

// Static files are served exclusively from the React build (client/dist,
// registered in defineRoutes). The old express.static on the repo root is
// gone — it exposed server.js, db/, and .env-adjacent files publicly.

// In-memory session store: sessionId -> { userId, username }
const sessions = new Map();

function createSession(userId, username) {
    const sessionId = crypto.randomBytes(32).toString('hex');
    sessions.set(sessionId, { userId, username });
    return sessionId;
}

function getSession(sessionId) {
    return sessionId ? sessions.get(sessionId) : null;
}

function destroySession(sessionId) {
    sessions.delete(sessionId);
}

// Auth middleware — protects API routes and HTML pages
function requireAuth(req, res, next) {
    const sessionId = req.cookies['sessionId'];
    const session = getSession(sessionId);
    if (!session) {
        // originalUrl, not path: when mounted via app.use('/api/x', requireAuth)
        // req.path is stripped to '/' and API calls would get a 302 instead of 401
        if (req.originalUrl.startsWith('/api/')) {
            return res.status(401).json({ error: 'Not authenticated' });
        }
        return res.redirect('/login');
    }
    req.deviceId = session.userId;
    req.username = session.username;
    next();
}

// Initialize database and device ID middleware
let db;

async function initializeDatabase() {
    try {
        db = new DatabaseService();
        await db.initialize();

        // Define routes after db is ready
        defineRoutes();

        console.log('Database and middleware initialized successfully');
    } catch (error) {
        console.error('Failed to initialize database:', error);
        process.exit(1);
    }
}

function defineRoutes() {
    // Auth routes (no auth required)
    app.post('/api/auth/register', [
        body('username').isString().trim().isLength({ min: 1, max: 50 }).escape(),
        body('password').isString().isLength({ min: 1 }),
        handleValidationErrors
    ], async (req, res) => {
        try {
            const hasUsers = await db.hasUsers();
            if (hasUsers) {
                return res.status(403).json({ error: 'Registration is closed' });
            }
            const { username, password } = req.body;
            const user = await db.createUser(username, password);
            // Groups are keyed by device_id with an FK to devices; auth users
            // reuse their user id as device id, so the devices row must exist
            await db.registerDevice(user.id);
            const sessionId = createSession(user.id, user.username);
            res.cookie('sessionId', sessionId, { httpOnly: true, sameSite: 'lax', maxAge: 365 * 24 * 60 * 60 * 1000 });
            res.json({ username: user.username });
        } catch (err) {
            res.status(400).json({ error: err.message });
        }
    });

    app.post('/api/auth/login', [
        body('username').isString().trim().isLength({ min: 1 }).escape(),
        body('password').isString().isLength({ min: 1 }),
        handleValidationErrors
    ], async (req, res) => {
        try {
            const { username, password } = req.body;
            const user = await db.verifyUser(username, password);
            if (!user) return res.status(401).json({ error: 'Invalid username or password' });
            // Upsert the devices row (see register) — also backfills users
            // created before this fix
            await db.registerDevice(user.id);
            const sessionId = createSession(user.id, user.username);
            res.cookie('sessionId', sessionId, { httpOnly: true, sameSite: 'lax', maxAge: 365 * 24 * 60 * 60 * 1000 });
            res.json({ username: user.username });
        } catch (err) {
            res.status(500).json({ error: 'Login failed' });
        }
    });

    app.post('/api/auth/logout', (req, res) => {
        const sessionId = req.cookies['sessionId'];
        destroySession(sessionId);
        res.clearCookie('sessionId');
        res.json({ ok: true });
    });

    app.get('/api/auth/me', (req, res) => {
        const session = getSession(req.cookies['sessionId']);
        if (!session) return res.status(401).json({ error: 'Not authenticated' });
        res.json({ username: session.username });
    });

    app.get('/api/auth/has-users', async (req, res) => {
        const hasUsers = await db.hasUsers();
        res.json({ hasUsers });
    });

    // Apply auth to all data API routes
    app.use('/api/config', requireAuth);
    app.use('/api/zipcodes', requireAuth);
    app.use('/api/locations', requireAuth);
    app.use('/api/panel-stock', requireAuth);

    app.get('/api/config', (req, res) => {
        res.json({
            googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY
        });
    });

// Builds the lookup response payload for one ZIP from the in-memory ZCTA
// data, or null when the ZIP isn't in the dataset. Center is the average of
// the outer-ring vertices (matches what the client markers expect).
function buildZipResponse(zipCode) {
    const geometry = zipcodeData[zipCode];
    if (!geometry) return null;

    let centerLat = 0;
    let centerLng = 0;
    let pointCount = 0;

    if (geometry.type === 'Polygon') {
        geometry.coordinates[0].forEach(coord => {
            centerLng += coord[0];
            centerLat += coord[1];
            pointCount++;
        });
    } else if (geometry.type === 'MultiPolygon') {
        geometry.coordinates.forEach(polygon => {
            polygon[0].forEach(coord => {
                centerLng += coord[0];
                centerLat += coord[1];
                pointCount++;
            });
        });
    }

    centerLat /= pointCount;
    centerLng /= pointCount;

    return {
        zipCode: zipCode,
        title: `ZIP ${zipCode}`,
        center: {
            lat: centerLat,
            lng: centerLng
        },
        formattedAddress: `ZIP Code ${zipCode}, USA`,
        geometry: JSON.stringify(geometry)
    };
}

// Zip code boundary lookup endpoint (using Census ZCTA data)
app.post('/api/zipcodes/lookup', [
    body('zipCode')
        .isString()
        .trim()
        .matches(/^\d{5}$/)
        .withMessage('ZIP code must be exactly 5 digits'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { zipCode } = req.body;

        // Check if zipcode data is loaded
        if (!zipcodeDataLoaded || !zipcodeData) {
            return res.status(503).json({
                error: 'ZIP code data not available. Server may still be loading.',
                zipCode: zipCode
            });
        }

        const responseData = buildZipResponse(zipCode);

        if (!responseData) {
            return res.status(404).json({
                error: 'ZIP code not found',
                zipCode: zipCode
            });
        }

        res.json(responseData);
    } catch (error) {
        console.error('Error looking up ZIP code:', error);
        res.status(500).json({ error: 'Failed to lookup ZIP code' });
    }
});

// Batch variant of the lookup above: one request resolves up to 250 ZIPs so
// large Panel Stock uploads (2,700+ rows) don't burn one rate-limited request
// per ZIP. Unknown ZIPs are reported in notFound rather than failing the call.
app.post('/api/zipcodes/lookup-batch', [
    body('zipCodes')
        .isArray({ min: 1, max: 250 })
        .withMessage('zipCodes must be an array of 1 to 250 entries'),
    body('zipCodes.*')
        .isString()
        .trim()
        .matches(/^\d{5}$/)
        .withMessage('Each ZIP code must be exactly 5 digits'),
    handleValidationErrors
], async (req, res) => {
    try {
        if (!zipcodeDataLoaded || !zipcodeData) {
            return res.status(503).json({
                error: 'ZIP code data not available. Server may still be loading.'
            });
        }

        const results = {};
        const notFound = [];
        for (const zipCode of new Set(req.body.zipCodes)) {
            const responseData = buildZipResponse(zipCode);
            if (responseData) {
                results[zipCode] = responseData;
            } else {
                notFound.push(zipCode);
            }
        }

        res.json({ results, notFound });
    } catch (error) {
        console.error('Error looking up ZIP codes in batch:', error);
        res.status(500).json({ error: 'Failed to lookup ZIP codes' });
    }
});

// Bulk CA ZIP color lookup — precomputed graph-coloring assignment so
// adjacent ZIP polygons never share a color on the Panel Stock Analysis map.
// See scripts/computeZipCaColors.js for how this is generated.
app.get('/api/zipcodes/colors', (req, res) => {
    res.json({ colors: caZipColors || {}, defaultColor: '#3b82f6' });
});

// Panel Stock Analysis uploads — parsed client-side (xlsx), stored as JSONB.
// Device-owned like location_groups; no group_type distinction needed since
// there's only one kind of record here.
app.get('/api/panel-stock/uploads', async (req, res) => {
    try {
        const deviceId = req.deviceId;
        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }
        const uploads = await db.getPanelStockUploads(deviceId);
        res.json(uploads);
    } catch (error) {
        console.error('Error fetching panel stock uploads:', error);
        res.status(500).json({ error: 'Failed to fetch panel stock uploads' });
    }
});

app.get('/api/panel-stock/uploads/:id', [
    param('id').isUUID().withMessage('Invalid upload ID'),
    handleValidationErrors
], async (req, res) => {
    try {
        const deviceId = req.deviceId;
        const upload = await db.getPanelStockUpload(req.params.id, deviceId);
        if (!upload) {
            return res.status(404).json({ error: 'Panel stock upload not found' });
        }
        res.json(upload);
    } catch (error) {
        console.error('Error fetching panel stock upload:', error);
        res.status(500).json({ error: 'Failed to fetch panel stock upload' });
    }
});

app.post('/api/panel-stock/uploads', [
    body('title').isString().trim().isLength({ min: 1, max: 200 }).withMessage('Title is required'),
    body('fileName').isString().trim().isLength({ min: 1, max: 255 }).withMessage('File name is required'),
    body('specialties').isArray().withMessage('Specialties must be an array'),
    body('rows').isArray().withMessage('Rows must be an array'),
    body('duplicateZips').optional().isArray(),
    handleValidationErrors
], async (req, res) => {
    try {
        const deviceId = req.deviceId;
        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }
        const { title, fileName, specialties, rows, duplicateZips } = req.body;
        const upload = await db.createPanelStockUpload(deviceId, { title, fileName, specialties, rows, duplicateZips });
        res.status(201).json(upload);
    } catch (error) {
        console.error('Error creating panel stock upload:', error);
        res.status(500).json({ error: 'Failed to create panel stock upload' });
    }
});

app.delete('/api/panel-stock/uploads/:id', [
    param('id').isUUID().withMessage('Invalid upload ID'),
    handleValidationErrors
], async (req, res) => {
    try {
        const deviceId = req.deviceId;
        await db.deletePanelStockUpload(req.params.id, deviceId);
        res.status(204).send();
    } catch (error) {
        if (error.message === 'Panel stock upload not found or access denied') {
            return res.status(404).json({ error: error.message });
        }
        console.error('Error deleting panel stock upload:', error);
        res.status(500).json({ error: 'Failed to delete panel stock upload' });
    }
});

app.get('/api/:groupType(locations|zipcodes)/groups', async (req, res) => {
    try {
        const deviceId = req.deviceId;
        const { groupType } = req.params;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const groups = await db.getLocationGroups(deviceId, groupType);
        res.json(groups);
    } catch (error) {
        console.error('Error fetching location groups:', error);
        res.status(500).json({ error: 'Failed to fetch location groups' });
    }
});

app.get('/api/:groupType(locations|zipcodes)/groups/:id', [
    param('id').isUUID().withMessage('Invalid group ID'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { id, groupType } = req.params;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const group = await db.getLocationGroup(id, deviceId, groupType);

        if (!group) {
            return res.status(404).json({ error: 'Location group not found' });
        }

        res.json(group);
    } catch (error) {
        console.error('Error fetching location group:', error);
        res.status(500).json({ error: 'Failed to fetch location group' });
    }
});

app.post('/api/:groupType(locations|zipcodes)/groups', [
    body('name')
        .isString()
        .trim()
        .isLength({ min: 1, max: 100 })
        .escape()
        .withMessage('Group name must be between 1-100 characters'),
    body('locations')
        .optional()
        .isArray()
        .withMessage('Locations must be an array'),
    body('locations.*.lat')
        .optional()
        .isFloat({ min: -90, max: 90 })
        .withMessage('Latitude must be between -90 and 90'),
    body('locations.*.lng')
        .optional()
        .isFloat({ min: -180, max: 180 })
        .withMessage('Longitude must be between -180 and 180'),
    body('locations.*.title')
        .optional()
        .isString()
        .trim()
        .isLength({ max: 200 })
        .escape()
        .withMessage('Title must be less than 200 characters'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { name, locations } = req.body;
        const { groupType } = req.params;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const group = await db.createLocationGroup(deviceId, name, locations || [], groupType);
        res.status(201).json(group);
    } catch (error) {
        console.error('Error creating location group:', error);
        res.status(500).json({ error: 'Failed to create location group' });
    }
});

app.put('/api/:groupType(locations|zipcodes)/groups/:id', [
    param('id').isUUID().withMessage('Invalid group ID'),
    body('name')
        .optional()
        .isString()
        .trim()
        .isLength({ min: 1, max: 100 })
        .escape()
        .withMessage('Group name must be between 1-100 characters'),
    body('locations')
        .optional()
        .isArray()
        .withMessage('Locations must be an array'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { id, groupType } = req.params;
        const { name, locations } = req.body;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const updates = {};
        if (name !== undefined) updates.name = name;
        if (locations !== undefined) updates.locations = locations;

        const updatedGroup = await db.updateLocationGroup(id, deviceId, updates, groupType);

        if (!updatedGroup) {
            return res.status(404).json({ error: 'Location group not found' });
        }

        res.json(updatedGroup);
    } catch (error) {
        console.error('Error updating location group:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location group not found' });
        } else {
            res.status(500).json({ error: 'Failed to update location group' });
        }
    }
});

app.delete('/api/:groupType(locations|zipcodes)/groups/:id', [
    param('id').isUUID().withMessage('Invalid group ID'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { id, groupType } = req.params;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        await db.deleteLocationGroup(id, deviceId, groupType);
        res.status(204).send();
    } catch (error) {
        console.error('Error deleting location group:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location group not found' });
        } else {
            res.status(500).json({ error: 'Failed to delete location group' });
        }
    }
});

app.post('/api/:groupType(locations|zipcodes)/groups/:id/locations', [
    param('id').isUUID().withMessage('Invalid group ID'),
    body('lat')
        .isFloat({ min: -90, max: 90 })
        .withMessage('Latitude must be between -90 and 90'),
    body('lng')
        .isFloat({ min: -180, max: 180 })
        .withMessage('Longitude must be between -180 and 180'),
    body('title')
        .isString()
        .trim()
        .isLength({ min: 1, max: 200 })
        .escape()
        .withMessage('Title must be between 1-200 characters'),
    body('color')
        .optional()
        .matches(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)
        .withMessage('Color must be a valid hex color'),
    body('geometry')
        .optional()
        .isString()
        .withMessage('Geometry must be a string (GeoJSON)'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { id, groupType } = req.params;
        const { lat, lng, title, color, geometry } = req.body;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const locationData = {
            lat: parseFloat(lat),
            lng: parseFloat(lng),
            title,
            color: color || '#3B82F6'
        };

        // Include geometry if provided
        if (geometry) {
            locationData.geometry = geometry;
        }

        const location = await db.addLocationToGroup(id, deviceId, locationData);
        res.status(201).json(location);
    } catch (error) {
        console.error('Error adding location:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location group not found' });
        } else {
            res.status(500).json({ error: 'Failed to add location' });
        }
    }
});

// NOTE: the reorder route must be registered before the :locationId route,
// otherwise "reorder" is captured as a :locationId and fails UUID validation
app.put('/api/:groupType(locations|zipcodes)/groups/:groupId/locations/reorder', [
    param('groupId').isUUID().withMessage('Invalid group ID'),
    body('locationIds')
        .isArray()
        .withMessage('locationIds must be an array')
        .custom((value) => {
            if (value.length > 1000) {
                throw new Error('Too many location IDs');
            }
            return value.every(id => typeof id === 'string');
        }),
    handleValidationErrors
], async (req, res) => {
    try {
        const { groupId, groupType } = req.params;
        const { locationIds } = req.body;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        await db.reorderLocations(groupId, deviceId, locationIds);

        // Get updated locations to return
        const locations = await db.getLocationsForGroup(groupId);
        res.json({ success: true, locations });
    } catch (error) {
        console.error('Error reordering locations:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location group not found' });
        } else {
            res.status(500).json({ error: 'Failed to reorder locations' });
        }
    }
});

app.put('/api/:groupType(locations|zipcodes)/groups/:groupId/locations/:locationId', [
    param('groupId').isUUID().withMessage('Invalid group ID'),
    param('locationId').isUUID().withMessage('Invalid location ID'),
    body('color')
        .optional()
        .matches(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)
        .withMessage('Color must be a valid hex color'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { groupId, locationId, groupType } = req.params;
        const { color } = req.body;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        const updates = {};
        if (color !== undefined) updates.color = color;

        const location = await db.updateLocation(groupId, locationId, deviceId, updates);
        res.json(location);
    } catch (error) {
        console.error('Error updating location:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location or group not found' });
        } else {
            res.status(500).json({ error: 'Failed to update location' });
        }
    }
});

app.delete('/api/:groupType(locations|zipcodes)/groups/:groupId/locations/:locationId', [
    param('groupId').isUUID().withMessage('Invalid group ID'),
    param('locationId').isUUID().withMessage('Invalid location ID'),
    handleValidationErrors
], async (req, res) => {
    try {
        const { groupId, locationId, groupType } = req.params;
        const deviceId = req.deviceId;

        if (!deviceId) {
            return res.status(400).json({ error: 'Device ID not found' });
        }

        await db.deleteLocation(groupId, locationId, deviceId);
        res.status(204).send();
    } catch (error) {
        console.error('Error deleting location:', error);
        if (error.message.includes('not found') || error.message.includes('access denied')) {
            res.status(404).json({ error: 'Location or group not found' });
        } else {
            res.status(500).json({ error: 'Failed to delete location' });
        }
    }
});

// ================================
// File uploads (spreadsheets/data files)
// ================================

const uploadsDir = path.join(__dirname, 'uploads');
fs.mkdirSync(uploadsDir, { recursive: true });

const UPLOAD_ALLOWED_EXTENSIONS = ['.csv', '.txt', '.xls', '.xlsx'];
const UPLOAD_ALLOWED_MIMETYPES = [
    'text/csv',
    'text/plain',
    'application/csv',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    // Windows browsers and CLI clients often report CSV/XLSX as a generic
    // binary stream; the extension allowlist is the authoritative check
    'application/octet-stream'
];

const upload = multer({
    storage: multer.diskStorage({
        destination: uploadsDir,
        filename: (req, file, cb) => {
            const safeName = path.basename(file.originalname).replace(/[^\w.\-]/g, '_');
            cb(null, `${Date.now()}-${crypto.randomBytes(4).toString('hex')}-${safeName}`);
        }
    }),
    limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB per file
    fileFilter: (req, file, cb) => {
        // Extension check in addition to MIME type: browsers report CSV/TXT
        // MIME types inconsistently across platforms
        const ext = path.extname(file.originalname).toLowerCase();
        const ok = UPLOAD_ALLOWED_EXTENSIONS.includes(ext) && UPLOAD_ALLOWED_MIMETYPES.includes(file.mimetype);
        if (ok) {
            cb(null, true);
        } else {
            cb(new Error(`Unsupported file type: ${file.originalname}. Allowed: CSV, TXT, XLS, XLSX.`));
        }
    }
});

app.use('/api/uploads', requireAuth);

app.post('/api/uploads', upload.array('files', 10), (req, res) => {
    if (!req.files || req.files.length === 0) {
        return res.status(400).json({ error: 'No files uploaded' });
    }
    res.status(201).json({
        files: req.files.map(file => ({
            name: file.filename,
            originalName: file.originalname,
            size: file.size,
            mimeType: file.mimetype
        }))
    });
});

app.get('/api/uploads', async (req, res) => {
    try {
        const names = await fs.promises.readdir(uploadsDir);
        const files = await Promise.all(names.map(async (name) => {
            const stats = await fs.promises.stat(path.join(uploadsDir, name));
            return { name, size: stats.size, uploadedAt: stats.mtime };
        }));
        files.sort((a, b) => new Date(b.uploadedAt) - new Date(a.uploadedAt));
        res.json(files);
    } catch (error) {
        console.error('Error listing uploads:', error);
        res.status(500).json({ error: 'Failed to list uploads' });
    }
});

app.get('/api/uploads/:name', (req, res) => {
    // path.basename guards against path traversal in the stored name
    const filePath = path.join(uploadsDir, path.basename(req.params.name));
    if (!fs.existsSync(filePath)) {
        return res.status(404).json({ error: 'File not found' });
    }
    res.download(filePath);
});

app.delete('/api/uploads/:name', async (req, res) => {
    try {
        const filePath = path.join(uploadsDir, path.basename(req.params.name));
        await fs.promises.unlink(filePath);
        res.status(204).send();
    } catch (error) {
        if (error.code === 'ENOENT') {
            return res.status(404).json({ error: 'File not found' });
        }
        console.error('Error deleting upload:', error);
        res.status(500).json({ error: 'Failed to delete file' });
    }
});

// Multer errors (size limit, rejected type) -> 400 JSON instead of a 500 page
app.use('/api/uploads', (err, req, res, next) => {
    if (err) {
        const message = err.code === 'LIMIT_FILE_SIZE'
            ? 'File too large. Maximum size is 10 MB.'
            : err.message;
        return res.status(400).json({ error: message });
    }
    next();
});

// ================================
// React SPA (client/dist) + fallback for client-side routes
// ================================

// Gated on the build existing so the same code path works in dev (where the
// Vite dev server is used instead) and production.
const clientDist = path.join(__dirname, 'client', 'dist');
if (fs.existsSync(path.join(clientDist, 'index.html'))) {
    app.use(express.static(clientDist));
    app.get(/^\/(?!api\/).*/, (req, res) => {
        res.sendFile(path.join(clientDist, 'index.html'));
    });
    console.log('Serving React client from client/dist');
} else {
    console.log('client/dist not found - run "npm run build" to serve the React client');
}
}


// Initialize database and start server
async function startServer() {
    try {
        // Load ZIP code data and initialize database in parallel
        await Promise.all([
            loadZipcodeData(),
            loadCaZipColors(),
            initializeDatabase()
        ]);

        app.listen(PORT, () => {
            console.log(`Server running on http://localhost:${PORT}`);
            console.log('Database persistence enabled');
        });
    } catch (error) {
        console.error('Failed to start server:', error);
        process.exit(1);
    }
}

// Graceful shutdown
process.on('SIGINT', () => {
    console.log('\nShutting down gracefully...');
    if (db) {
        db.close();
    }
    process.exit(0);
});

process.on('SIGTERM', () => {
    console.log('SIGTERM received, shutting down gracefully...');
    if (db) {
        db.close();
    }
    process.exit(0);
});

startServer();